# Generated by Django 5.0.2 on 2024-04-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateTime_created',
            new_name='datetime_created',
        ),
    ]
